version: '3.1'

services:
  mysql:
    image: mysql:5
    ports:
      - 127.0.0.1:36000-37000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
  postgres:
    image: postgres:9
    ports:
      - 127.0.0.1:36000-37000:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
